### ISSUE TITLE
環境構築

### ISSUE THREAD

**Issue by purotoko321** [purotoko321/housework_sharing#1]
ローカル環境でDockerを作成し
herokuへデプロイするまで

**Comment by purotoko321** [comment]
なんかherokuでへデプロイする際にエラー出た。
色々やってみたが解決できないので一旦保留にする。
最終的にはAWSにデプロイ予定だし、、

**Comment by purotoko321** [comment]
以下コマンドでwebサーバーコンテナが立ち上がり、かつrails newできた
```
docker-compose run web rails new . --force --database=mysql
```

Gemfileが新しくなったのでイメージをリビルド
```cmd
docker-compose build
```

config/database.yml
のdb設定を変更。passwordに設定した理由としてはdocker-composeでMYSQL_ROOT_PASSWORD:にpasswordと設定したため。
dbはdocker-composeのdepends_on:でdbとしているから
``` yml
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db
```

DBを作る
```
docker-compose run web rails db:create
```

dockerコンテナを作成、起動
```
docker-compose up
```


---
## herokuへデプロイするまで
heroku アプリの作成
```
heroku login
heroku container:login
heroku create housework-sharing
```
アプリにmysqlアドオンを追加する
無料のはバージョン5系までしかないらしく
本来ならばバージョンを揃えないと予期せぬエラーが出る。
ただ、最終的なデプロイさきはec2の予定なのでバージョン違いのままある程度進めるならそうしたい
```
heroku addons:create cleardb:ignite -a housework-sharing
```

config/database.ymlに本番環境用の設定を追加する
```yml
production:
  <<: *default
  database: <%= ENV['APP_DATABASE'] %>
  username: <%= ENV['APP_DATABASE_USERNAME'] %>
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
  host: <%= ENV['APP_DATABASE_HOST'] %>
```

herokuの接続先状況を確認するコマンド
```
heroku config -a housework-sharing
→CLEARDB_DATABASE_URL: mysql://b6e1cd31bf8f51:65763857@us-cdbr-east-04.cleardb.com/heroku_26db91f3b479346?reconnect=true
```

herokuの環境変数を設定
```
heroku config:add APP_DATABASE='heroku_26db91f3b479346' -a housework-sharing
heroku config:add APP_DATABASE_USERNAME='b6e1cd31bf8f51' -a housework-sharing
heroku config:add APP_DATABASE_PASSWORD='65763857' -a housework-sharing
heroku config:add APP_DATABASE_HOST='us-cdbr-east-04.cleardb.com' -a housework-sharing
```
環境変数を設定
```
heroku config:add RAILS_SERVE_STATIC_FILES='true' -a housework-sharing
```


サーバーのポートバインドの時間がデフォルト６０秒だが
足りない場合があるので120に伸ばしておく
https://tools.heroku.support/limits/boot_timeout

コンテナの削除を行う
```
docker-compose down
```

以下のファイルがあるとherokuにアップロードするときエラーになるので消す
```
rm src/tmp/pids/server.pid
```

herokuのコンテナレジストリへpushする
```
heroku container:push web -a housework-sharing
```
herokuのコンテナレジストリにあげたイメージをherokuの方へリリースしていく
```
heroku container:release web -a housework-sharing
```

リリース後、DBマイグレーションを実行していく
```
heroku run bundle exec rake db:migrate RAILS_ENV=production -a housework-sharing
```
↓なんかエラー出た
[M1 MacでHeroku containerにデプロイしたら `Exec format error` と出て困った話](https://zenn.dev/daku10/articles/m1-heroku-container-trouble-exec-format-error)
→試したこと
[M1 MacでHeroku containerにデプロイしたら `Exec format error` と出て困った話](https://zenn.dev/daku10/articles/m1-heroku-container-trouble-exec-format-error)
下記コマンドでビルドしてから同じ手順
```
docker buildx build . --platform linux/amd64
```
